CC = gcc
LDFLAGS = -L/usr/lib -lglut -lGLU -lGL -lm
IFLAGS  = -I/usr/include 
CCFLAGS = -g -Wall -O2

EXENAME = saltamontes

TARGETS = saltamontes.c

default:
	$(CC) $(TARGETS) $(CCFLAGS) $(IFLAGS) $(LDFLAGS) -o $(EXENAME)
